### ISSUE TITLE
Update site link is broken

### ISSUE THREAD

**Issue by levsa** [alfsch/workspacemechanic#1]
This link is broken: http://alfsch.github.io/eclipse-updates/workspacemechanic/

**Comment by alfsch** [comment]
I currently pasted the link into my eclipse (install new software dialog) and the Site worked. The Site is a p2 repo and not browsable with a web browser.

**Comment by himanshu612** [comment]
I too tired with the link into my eclipse  (install new software dialog)  http://alfsch.github.io/eclipse-updates/workspacemechanic/ . It seems to be broken, Can you check it one more time.

**Comment by levsa** [comment]
You were right it works in Eclipse. I tried to browse an got 404 because of missing index.html.

**Comment by alfsch** [comment]
I've added an index.html to the update site. Hopefully this solves some Problems. Please use the https secured update site:

https://alfsch.github.io/eclipse-updates/workspacemechanic/

**Comment by alfsch** [comment]
@himanshu612 Could you provide some Infos about the eclipse version and the os you are using?

**Comment by himanshu612** [comment]
Sorry.. it worked fine for me now. My mistake.

**Comment by alfsch** [comment]
No Problem. If somebody checks if the index.html is sufficient and working, I will close the issue.

**Comment by instagibb** [comment]
@alfsch Are you planning to get the Eclipse Marketplace links updated?

**Comment by alfsch** [comment]
@instagibb I've written several messages/e-mails, but no response. If somebody knows how to do this, please let me know.

**Comment by instagibb** [comment]
@alfsch Thanks for the update. Are you still in contact with the original owner? Perhaps they would be willing to use their account to update it? The only other thing I could suggest is asking on the eclipse forums?

**Comment by markiewb** [comment]
The update-site works fine. This issue can be closed

**Comment by Lonzak** [comment]
Update: The marketplace Install link works again. Alfsch is now also maintainer...So this issue can indeed be closed.
